//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gnu.Getopt.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gnu.Getopt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0}: option &apos;&apos;{1}&apos;&apos; is ambiguous に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string getoptAmbigious {
            get {
                return ResourceManager.GetString("getoptAmbigious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}: option &apos;&apos;--{1}&apos;&apos; doesn&apos;t allow an argument に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string getoptArguments1 {
            get {
                return ResourceManager.GetString("getoptArguments1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}: option &apos;&apos;{1}{2}&apos;&apos; doesn&apos;t allow an argument に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string getoptArguments2 {
            get {
                return ResourceManager.GetString("getoptArguments2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}: illegal option -- {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string getoptIllegal {
            get {
                return ResourceManager.GetString("getoptIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}: invalid option -- {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string getoptInvalid {
            get {
                return ResourceManager.GetString("getoptInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid value {0} for parameter &apos;has_arg&apos;  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string getoptInvalidValue {
            get {
                return ResourceManager.GetString("getoptInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}: option &apos;&apos;{1}&apos;&apos; requires an argument に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string getoptRequires {
            get {
                return ResourceManager.GetString("getoptRequires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}: option requires an argument -- {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string getoptRequires2 {
            get {
                return ResourceManager.GetString("getoptRequires2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}: unrecognized option &apos;&apos;--{1}&apos;&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string getoptUnrecognized {
            get {
                return ResourceManager.GetString("getoptUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}: unrecognized option &apos;&apos;{1}{2}&apos;&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string getoptUnrecognized2 {
            get {
                return ResourceManager.GetString("getoptUnrecognized2", resourceCulture);
            }
        }
    }
}
